repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
        name: Detect secrets with Gitleaks
        entry: gitleaks detect --source . --verbose
        language: system
        stages: [commit]
        pass_filenames: false
